name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - uses: editorconfig-checker/action-editorconfig-checker@v1
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: htynkn/speed-monitor:latest

  cross_compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Cross tool
        run: cargo install cross
      - name: Build
        run: cross build --target x86_64-unknown-linux-gnu --release
      - name: Copy exec file
        run: mkdir -p packing/terra-master/speedmonitor/usr/local/speedmonitor/ && cp target/x86_64-unknown-linux-gnu/release/speed-monitor packing/terra-master/speedmonitor/usr/local/speedmonitor/ && chmod +x packing/terra-master/speedmonitor/usr/local/speedmonitor/*
      - uses: htynkn/terra-master-packing-action@master
        name: Terra-Master packing
        with:
          folder-name: packing/terra-master/speedmonitor/
          arch: x86_apps
          tpk-name: speedmonitor
      - uses: actions/upload-artifact@v2
        with:
          name: tpk
          path: "*.tpk"
